### ISSUE TITLE
Error with tray icon

### ISSUE THREAD

**Issue by erhoppe** [andrepolischuk/thomas#10]
Clicking on the button in the tray produces an empty black box. When I try to unenable the tray icon, I get the following error:

**A JavaScript error occurred in the main process**
Uncaught Exception:
TypeError: Cannot read property 'show' of undefined
    at Array.data.subscribe (~/thomas/app/createWindow.js:112:15)
    at notify (~/thomas/node_modules/dact/dist/index.js:65:18)
    at merge (~/thomas/node_modules/dact/dist/index.js:83:9)
    at ~/thomas/node_modules/dact-electron/dist/index.js:35:16
    at Object.emit ~/thomas/node_modules/dact/dist/index.js:115:12)
    at EventEmitter.<anonymous> (~/thomas/node_modules/dact-electron/dist/index.js:20:12)
    at emitTwo (events.js:125:13)
    at EventEmitter.emit (events.js:213:7)
    at WebContents.<anonymous> (~/thomas/node_modules/electron/dist/resources/electron.asar/browser/api/web-contents.js:266:13)
    at emitTwo (events.js:125:13)

I'm running Ubuntu 16.04.4 LTS (xenial).

**Comment by andrepolischuk** [comment]
sorry for waiting, I’m going to fix this next week

**Comment by fcanela** [comment]
Same error raises to me just after pressing the arrows to increase-decrease the pomodoro time.

**Comment by karatesoup** [comment]
Same issue here running Ubuntu 18.04.2 LTS (Bionic Beaver). Tray functionality would be really great!!

**Comment by ChristopheChanteur** [comment]
same errors with javascrit
Win10 user

**Comment by ChristopheChanteur** [comment]
I can't even use the app, since it appears from even opening the app, straight after installation. 
I need to kill the process in task manager

**Comment by eringiglio** [comment]
I have this same problem. What's up?
